/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings workers/spotify-stats/src/bindings.d.ts` (hash: 1feebb95b1ed7ecdcb3024e3d74e757d)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	LOGIN_RATE_LIMITER: RateLimit;
	PUBLIC_SITE_ORIGIN: "https://www.lukeharjulin.com";
	RECOMMENDATIONS_ENABLED: "true";
	LISTENING_PASSPHRASE: string;
	LISTENING_SESSION_SECRET: string;
	SPOTIFY_CLIENT_ID: string;
	SPOTIFY_CLIENT_SECRET: string;
	SPOTIFY_REFRESH_TOKEN: string;
	LASTFM_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_ORIGIN" | "RECOMMENDATIONS_ENABLED" | "LISTENING_PASSPHRASE" | "LISTENING_SESSION_SECRET" | "SPOTIFY_CLIENT_ID" | "SPOTIFY_CLIENT_SECRET" | "SPOTIFY_REFRESH_TOKEN" | "LASTFM_API_KEY">> {}
}
